### ISSUE TITLE
Ignore certain folders/files like node_modules or /bin folder

### ISSUE THREAD

**Issue by carlos-xpln** [beicause/call-graph#10]
This extension is just awesome!

It would be great if we can ignore certain folders & files to keep the graph clean (without obvious calls like _map_, _forEach_, etc).

Thanks in advance

**Comment by jotavemonte** [comment]
@carlos-xpln https://github.com/beicause/call-graph/issues/6
It's already possible to ignore some patterns

**Comment by zdila** [comment]
`.callgraphignore` doesn't work for me

**Comment by carlos-xpln** [comment]
seems to work for me. However, it doesn't ignore files like /bin/..../node_modules/... etc. Only files at the root of the project.
