### ISSUE TITLE
请问支持c/c++吗

### ISSUE THREAD

**Issue by lcax200000** [beicause/call-graph#11]
想在c/c++中使用，请问可以支持吗

**Comment by beicause** [comment]
![Screenshot_20230219_092248_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/75941842/219907101-0d325458-8c2a-4b62-a180-7de16fac7507.jpg)
理论上支持show call hierarchy就能用

**Comment by Erik-k** [comment]
This does not work for C code. At least I have not been able to get it to work with my C code. I just get this error: "Can't resolve entry function" every time I try to use it.
