### ISSUE TITLE
Depth

### ISSUE THREAD

**Issue by carlos-xpln** [beicause/call-graph#12]
Hello there. I have another question / suggestion:

Is there a way to manage the number of levels that you want to go trough? I mean... I have a use case where I only want to generate the incoming call-graph of all the direct (one level) methods, with their respective file subgraphs?

**Comment by beicause** [comment]
Sounds good. But I don't have much time to improve this project. PR welcome.

**Comment by AshkanArabim** [comment]
Just to add to this (for anyone who eventually decides to implement this) maybe also add an option to limit the graph depth to the current project (vscode directory)?

For example, when I generate an outgonig graph from a function, I have no interest in seeing Python's built-in functions such as `print` and `cast`.

**Comment by jotavemonte** [comment]
@AshkanArabim Hey, you can use the `.callgraphignore` file to achieve what you want. You just need to ignore your Python path and maybe a virtual environment if you are using it.

See: https://github.com/beicause/call-graph/issues/16#issuecomment-1911309703
