### ISSUE TITLE
Ignore file not mentioned in the readme

### ISSUE THREAD

**Issue by jotavemonte** [beicause/call-graph#14]
The `.callgraphignore` was added at #6 , but there's no mention of it or of how to use it in the readme file.

**Comment by yaomengsi** [comment]
According to the source code, it is necessary to add file configuration in the workspace configuration file `${workspace}/.callgraphignore`.

```
import * as pm from 'picomatch'
```

```
        const graph = await callNodeFunction(entry[0], item => {
            if (ignoreFile === null) return false
            const patterns = fs
                .readFileSync(ignoreFile)
                .toString()
                .split('\n')
                .filter(str => str.length > 0)
                .map(str => path.resolve(workspace.fsPath, str))
            return pm(patterns)(item.uri.fsPath)
        })
```

[pm reference](https://github.com/micromatch/picomatch)

so, `.callgraphignore` would like

```
**ignore/path**
```

**Comment by zdx3578** [comment]
.map(str => path.resolve(workspace.fsPath, str))

so just ignore in workspace ?

**Comment by beicause** [comment]
see #16
