### ISSUE TITLE
any work .callgraphignore file  example ?

### ISSUE THREAD

**Issue by zdx3578** [beicause/call-graph#16]
my   .callgraphignore still dont work

**Comment by seshasaisuhashdesu** [comment]
Hey @beicause 

This tool is really great. But I need to ignore some folders/files from showing up in the call graph. 
Could you please atleast update how to use this .callgraphignore file. How should I list my ignore config? 

Hey @zdx3578. Any luck regarding this?

**Comment by beicause** [comment]
Just published a new version. Now it uses [node-ignore](https://github.com/kaelzhang/node-ignore) for `.callgraphignore`

**Comment by sulfurandcu** [comment]
.callgraphignore doesn't work in windows, i just fixed it in #19

**Comment by sulfurandcu** [comment]
before the author merges and updates the extention, you can follow below steps to use callgraphignore. in Windows.
1. open C:\Users\your_user_name\.vscode\extensions\luozhihao.call-graph-1.1.3\out\extension.js
2. locate to line 42: const itemPath = item.uri.fsPath.replace(`${workspace.fsPath}/`, '');
3. replace `${workspace.fsPath}/` with `${workspace.fsPath}\\`
4. done!

**Comment by sulfurandcu** [comment]
before the author merges and updates the extention, you can follow below steps to use .callgraphignore in Windows.
1. open C:\Users\XXXX\\.vscode\extensions\luozhihao.call-graph-1.1.3\out\extension.js
2. locate to line 42:
```
const itemPath = item.uri.fsPath.replace(`${workspace.fsPath}/`, '');
```
3. replace `${workspace.fsPath}/` with `${workspace.fsPath}\\`
4. done!
