### ISSUE TITLE
Cannot export svg or dot file

### ISSUE THREAD

**Issue by cnbebop** [beicause/call-graph#3]
When I click the 'save as svg' button, there was no reaction. Then I opened dev tools and found the exception:
![exception](https://user-images.githubusercontent.com/41517534/169307467-b99be04d-cea2-4732-9451-716f92c99a2e.png)

**Comment by beicause** [comment]
Fixed in v1.1.1

**Comment by cnbebop** [comment]
> 

So quick. Thank you : )
