### ISSUE TITLE
Can't run any commands

### ISSUE THREAD

**Issue by jamesWalker55** [beicause/call-graph#31]
When I try to use any of the commands it simply shows an error that the command doesn't exist:

![image](https://github.com/user-attachments/assets/7844b48f-96c6-4c54-8374-4fb174aa58df)

```
command 'CallGraph.showIncomingCallGraph' not found
```

I've tried this on both Windows and MacOS, both give the same error

**Comment by beicause** [comment]
Fixed in https://github.com/beicause/call-graph/commit/fb129eb3830b5737d2769deb384b0ff93abff10b, please try v1.2.3.

**Comment by jamesWalker55** [comment]
Can confirm it is indeed working now, many thanks!
