### ISSUE TITLE
Can't get outgoing calls graph

### ISSUE THREAD

**Issue by nkelly1322** [beicause/call-graph#9]
I get a complete incoming calls graph, but no outgoing.  Whenever I attempt to create an outgoing calls graph I get a graph with only 1 node, the call I tried to originate from.

Using clang language server with a compile_commands.json made from Bear Intercept-Build

Any notion of how I could fix/troubleshoot this?

**Comment by beicause** [comment]
Duplicate of #1, #7,  #11
